version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BGCOLOR=white
      - FGCOLOR=black
  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
